### ISSUE TITLE
Function error

### ISSUE THREAD

**Issue by toddsantoro** [AdamMoses-GitHub/MMM-CollegeFootballTop25#2]
There seems to be an error in the code (node_helper.js) 

`Whoops! There was an uncaught exception...
TypeError: aptop25ncaaf.getAPTop25NCAAFRankingsData is not a function
    at Class.updatePollData (/home/pi/MagicMirror/modules/MMM-CollegeFootballTop25/node_helper.js:58:21)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-CollegeFootballTop25/node_helper.js:36:18)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:513:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by JBIGGI3** [comment]
The later versions of MagicMirror removed the node_helper.js module, but it can be copied and pasted into the same path as previous versions without breaking anything (to my knowledge). First version I picked was 2.1.0, and it worked for me along with my edits to the ap-top25-ncaaf module, which is a dependency for this one. Check the node_helper module here https://github.com/MichMich/MagicMirror/tree/v2.1.0/modules/node_modules/node_helper and the ap-top25-ncaaf module here https://github.com/JBIGGI3/NPMJS-ap-top25-ncaaf (also check original owner to see if he merged the pull request for easier installation).
